enum ESTADOS_DIRECTLENDING_ENUM {
  EN_REVISION = 1,
  APROBADO,
  PRECONCEDIDO,
  FIRMA_SOLICITADA,
  GENERANDO_CONTRATO,
  CONTRATO_NO_ENVIADO,
  PENDIENTE_FIRMA,
  FIRMADO,
  PENDIENTE_PAGO,
  CONCEDIDO,
  PARCIALMENTE_PAGADO,
  PAGADO,
  DENEGADO,
}

export { ESTADOS_DIRECTLENDING_ENUM };
