enum firmaCesionesEnum {
  PENDIENTE_FIRMA_DIGITAL = 1,
  FIRMADA_DIGITALMENTE,
  PENDIENTE_FIRMA_ANTE_NOTARIO,
  FIRMA_ANTE_NOTARIO_SOLICITADA,
  SOLICITUD_FIRMA_CONFIRMADA,
  CONTRADO_GENERADO,
  CONTRATO_ENVIADA_ANTE_NOTARIO,
  FIRMADA_ANTE_NOTARIO,
  FINALIZADA,
}

export { firmaCesionesEnum };
