export const tabsEnum = {
  DATOS: 0,
  DIRECCIONES: 1,
  CONTACTOS: 2,
  CUENTAS_BANCARIAS: 3,
  DOCUMENTACION: 4,
  OPERACIONES: 5,
  EFECTOS: 6,
  CESIONES: 7,
  CUENTA_CLIENTE: 8,
  PRAS: 9,
  ERP: 10,
  RIESGO: 11,
};
