import { ESTADOS_DIRECTLENDING_ENUM } from '@shared/enum/enumEstadosDirectLending';

export const TABLE_VALUES = {
  HISTORIAL_DIRECT_LENDING: [
    ESTADOS_DIRECTLENDING_ENUM.PAGADO,
    ESTADOS_DIRECTLENDING_ENUM.DENEGADO,
  ],
  DIRECT_LENDING: [
    ESTADOS_DIRECTLENDING_ENUM.EN_REVISION,
    ESTADOS_DIRECTLENDING_ENUM.APROBADO,
    ESTADOS_DIRECTLENDING_ENUM.FIRMA_SOLICITADA,
    ESTADOS_DIRECTLENDING_ENUM.PRECONCEDIDO,
    ESTADOS_DIRECTLENDING_ENUM.GENERANDO_CONTRATO,
    ESTADOS_DIRECTLENDING_ENUM.CONTRATO_NO_ENVIADO,
    ESTADOS_DIRECTLENDING_ENUM.PENDIENTE_FIRMA,
    ESTADOS_DIRECTLENDING_ENUM.FIRMA_SOLICITADA,
    ESTADOS_DIRECTLENDING_ENUM.FIRMADO,
    ESTADOS_DIRECTLENDING_ENUM.PENDIENTE_PAGO,
    ESTADOS_DIRECTLENDING_ENUM.CONCEDIDO,
    ESTADOS_DIRECTLENDING_ENUM.PARCIALMENTE_PAGADO,
  ],
};
